server:
  port: 8080

spring:
  application:
    name: bot

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false

bot:
  commands:
    start:
      name: "/start"
      description: "Начало работы"
      message: "Добро пожаловать! Используйте /help, чтобы посмотреть доступные команды."
    help:
      name: "/help"
      description: "Список доступных команд"
      header: "Доступные команды:"
    track:
      name: "/track"
      description: "Добавить ссылку"
      ask-link-message: "Введите ссылку:"
      already-tracked-message: "Ссылка уже отслеживается"
      ask-tags-message: "Введите теги через запятую (или /skip):"
      success-message: "Ссылка успешно добавлена!"
      cancel-message: "Процесс отслеживания отменён."
      skip-command: "/skip"
      cancel-command: "/cancel"
    unknown:
      name: "unknown"
      description: "Неизвестная команда"
      message: "Неизвестная команда. Воспользуйтесь /help."

logging:
  level:
    root: INFO
    org.springframework: WARN

